#!/usr/bin/env bash

echo "----> EXPORT STATIC HOST $AWS_STATIC_PREFIX/$SOURCE_VERSION"
export STATIC_PATH="/$AWS_STATIC_PREFIX/$SOURCE_VERSION"
export STATIC_SERVER="//s3-${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_BUCKET_NAME}"
